### ISSUE TITLE
При нажатии на 10 класс переходит на 11 класс

### ISSUE THREAD

**Issue by isupo** [S1riyS/CONTESTER#1]
![image](https://user-images.githubusercontent.com/6972174/173882865-7b17668b-035f-482c-845d-cc3a8bc8b31f.png)
![image](https://user-images.githubusercontent.com/6972174/173882912-571ee9ec-3223-4922-85f6-99f8ba560b07.png)

**Comment by S1riyS** [comment]
Недавно обновил ветку master, можете попробовать переустановить проект
