### ISSUE TITLE
werkzeug version error

### ISSUE THREAD

**Issue by isupo** [S1riyS/CONTESTER#2]
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/home/sisupov/Рабочий стол/selfproject/CONTESTER/venv/lib/python3.8/site-packages/werkzeug/security.py)

Werkzeug=2.0.3 to requirements.txt

**Comment by S1riyS** [comment]
Изменил на версию 2.0.3, спасибо
